# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://SimonSungm.github.io
date_format: "ordinal"
title: SimonSungm
subtitle: ""
description: "I am a graduate student from school of cyber science and technology, ZJU."
keywords: Operating System Security
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jiadong Sun
organization: 
organization_url: 
github_username: SimonSungm
location: Hangzhou, China
email: simonsungm@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: Wiki

  - 
    href: /class/
    label: Course

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About



# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

    course:
        output: true
        permalink: /class/:path/

repository: SimonSungm/SimonSungm.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: 
#    repo: 
#    oauth:
#        client_id: 
#        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: SimonSungm
    repo: blogtalk
    clientID: 122da303c62679712930
    clientSecret: 3ed7375f80fe7cd44bbf16161b1015ced21154ed
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
